import fs from 'node:fs/promises';
import { buildDayTradeDecision, computeIntradayMetrics, getSessionPhase, type DayTradeDecisionInput, type IntradayBar } from '../src/intraday';
import { getTradingProfile, WATCHLIST } from '../src/tradingProfiles';

const FROM='2026-07-17',TO='2026-09-15',DAILY_FROM='2026-03-01',OPEN=570,CLOSE=960,OR_END=585;
const UNIVERSE:Record<string,string>={AAPL:'QQQ',MSFT:'QQQ',GOOGL:'QQQ',AMZN:'QQQ',META:'QQQ',NFLX:'QQQ',ADBE:'IGV',NOW:'IGV',PANW:'IGV',CRWD:'IGV',PLTR:'IGV',QCOM:'SOXX',INTC:'SOXX',ARM:'SOXX',TSM:'SOXX',MRVL:'SOXX',SMCI:'SOXX',ANET:'XLK',COHR:'XLK',CIEN:'XLK',...Object.fromEntries(WATCHLIST.map(s=>[s,getTradingProfile(s).benchmark]))};
type Raw=IntradayBar&{epoch:number};type Daily={date:string;close:number};const epoch=(s:string)=>Math.floor(new Date(`${s}T00:00:00Z`).getTime()/1000);const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;const ma=(a:number[],n:number)=>a.length>=n?mean(a.slice(-n)):null;const sleep=(n:number)=>new Promise(r=>setTimeout(r,n));
function ny(ms:number){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms));const g=(t:string)=>p.find(x=>x.type===t)?.value??'';const time=`${g('hour')}:${g('minute')}`;const[h,m]=time.split(':').map(Number);return{date:`${g('year')}-${g('month')}-${g('day')}`,time,minute:h*60+m}}
async function chart(s:string,i:'5m'|'1d'){const f=i==='5m'?FROM:DAILY_FROM,u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(s)}?period1=${epoch(f)}&period2=${epoch(TO)}&interval=${i}&includePrePost=false&events=div%2Csplits`;const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0 stock-dashboard-gapfill','Accept':'application/json'}});if(!r.ok)throw new Error(`${s} ${i} ${r.status}`);const j:any=await r.json(),x=j?.chart?.result?.[0];if(!x)throw new Error(`${s} no data`);const q=x.indicators?.quote?.[0]??{};if(i==='1d'){const o:Daily[]=[];for(let k=0;k<(x.timestamp??[]).length;k++){const c=q.close?.[k];if(Number.isFinite(c))o.push({date:new Date(x.timestamp[k]*1000).toISOString().slice(0,10),close:+c})}return o}const o:Raw[]=[];for(let k=0;k<(x.timestamp??[]).length;k++){const a=q.open?.[k],h=q.high?.[k],l=q.low?.[k],c=q.close?.[k],v=q.volume?.[k];if(![a,h,l,c].every(Number.isFinite))continue;const p=ny(x.timestamp[k]*1000);if(p.minute<OPEN||p.minute>=CLOSE)continue;o.push({...p,epoch:x.timestamp[k]*1000,open:+a,high:+h,low:+l,close:+c,volume:Number(v)||0})}return o}
function group(a:Raw[]){const m=new Map<string,Raw[]>();for(const b of a){if(!m.has(b.date))m.set(b.date,[]);m.get(b.date)!.push(b)}return m}function bias(d:Daily[],date:string):'LONG'|'SHORT'|'NEUTRAL'{const p=d.filter(x=>x.date<date).map(x=>x.close);if(p.length<60)return'NEUTRAL';const c=p.at(-1)!,m20=ma(p,20)!,m60=ma(p,60)!;return c>m20&&m20>m60?'LONG':c<m20&&m20<m60?'SHORT':'NEUTRAL'}function market(s:Daily[],q:Daily[],date:string):'RISK_ON'|'NEUTRAL'|'RISK_OFF'{const a=s.filter(x=>x.date<date).map(x=>x.close),b=q.filter(x=>x.date<date).map(x=>x.close);if(a.length<50||b.length<50)return'NEUTRAL';const ac=a.at(-1)!,bc=b.at(-1)!,a20=ma(a,20)!,a50=ma(a,50)!,b20=ma(b,20)!,b50=ma(b,50)!;if(ac>a20&&a20>a50&&bc>b20&&b20>b50)return'RISK_ON';if(ac<a20&&a20<a50&&bc<b20&&b20<b50)return'RISK_OFF';return'NEUTRAL'}
function simulate(day:Raw[],idx:number,m:any,stopAtr=.65,targetR=2){const entry=day[idx].open,atr=m.intradayAtr??Math.max(entry*.002,.01),c=[m.vwap!==null?m.vwap+atr*.25:null,m.orLow!==null?m.orLow+atr*.2:null,m.recentHigh!==null?m.recentHigh+atr*.1:null].filter((v):v is number=>v!==null&&v>entry),struct=c.length?Math.min(...c):entry+atr*.5,stop=Math.max(entry+atr*stopAtr,struct),risk=Math.max(.01,stop-entry),target=entry-targetR*risk;let exit=day.at(-1)!.close,out='EOD';for(let j=idx;j<day.length;j++){const b=day[j];if(b.high>=stop){exit=stop;out=b.low<=target?'STOP_SAME_BAR':'STOP';break}if(b.low<=target){exit=target;out='TARGET';break}}const gross=(entry-exit)/risk,cost=(entry*.0004)/risk;return{entry,stop,target,outcome:out,netR:gross-cost}}
const stats=(x:any[])=>{const r=x.map(z=>z.trade.netR),w=r.filter(v=>v>0),l=r.filter(v=>v<0),pos=w.reduce((a,b)=>a+b,0),neg=-l.reduce((a,b)=>a+b,0);return{n:x.length,winRate:x.length?w.length/x.length*100:0,avgR:mean(r),totalR:r.reduce((a,b)=>a+b,0),pf:neg?pos/neg:null}};
await fs.mkdir('backtest-output-v6-gapfill',{recursive:true});const[spy,qqq]=await Promise.all([chart('SPY','1d') as Promise<Daily[]>,chart('QQQ','1d') as Promise<Daily[]>]);const benches=[...new Set(Object.values(UNIVERSE))],bm=new Map<string,Map<string,Raw[]>>();for(const b of benches){try{bm.set(b,group(await chart(b,'5m') as Raw[]));await sleep(100)}catch(e){console.warn('bench',b,e)}}const setups:any[]=[];const skipped:any[]=[];
for(const[symbol,bench]of Object.entries(UNIVERSE)){try{const bars=await chart(symbol,'5m') as Raw[];await sleep(100);const daily=await chart(symbol,'1d') as Daily[];await sleep(100);const mp=group(bars),dates=[...mp.keys()].sort(),bp=bm.get(bench);if(!bp)continue;for(let di=1;di<dates.length;di++){const date=dates[di],day=mp.get(date)!,prev=mp.get(dates[di-1])!,bd=bp.get(date)??[];if(day.length<30||prev.length<30||bd.length<30)continue;const gap=(day[0].open/prev.at(-1)!.close-1)*100;if(gap<3)continue;const mode=market(spy,qqq,date);if(mode==='RISK_ON')continue;const db=bias(daily,date);let sig:any=null;for(let i=0;i<day.length;i++){const bar=day[i];if(bar.minute<600)continue;const pd=dates.slice(Math.max(0,di-10),di),sh:IntradayBar[]=[],bh:IntradayBar[]=[];for(const d of pd){sh.push(...(mp.get(d)??[]));bh.push(...(bp.get(d)??[]))}sh.push(...day.slice(0,i+1));bh.push(...bd.filter(x=>x.minute<=bar.minute));const m=computeIntradayMetrics(sh,bh);m.stale=false;m.marketOpen=true;m.phase=getSessionPhase(bar.minute,'Mon');const input:DayTradeDecisionInput={metrics:m,dailyBias:db,marketMode:mode,accountSizeUsd:100000,riskPerTradePct:.5,dailyMaxLossPct:1.5,realizedPnlUsd:0,maxAllocationPct:25,bid:null,ask:null,hasCatalyst:false};const base=buildDayTradeDecision(input);const structural=(m.rvol??0)>=1.5&&m.currentPrice!==null&&m.vwap!==null&&m.currentPrice<m.vwap&&m.vwapSlopeUp===false&&m.benchmarkAboveVwap===false&&(m.relativeStrengthPct??Infinity)<=-1&&m.orReady&&m.orLow!==null&&m.currentPrice<m.orLow&&base.shortScore>=70;if(structural&&i+1<day.length){const gapDollars=m.sessionOpen!==null&&m.previousClose!==null?m.sessionOpen-m.previousClose:null;const fill=gapDollars&&gapDollars>0&&m.currentPrice!==null?(m.sessionOpen!-m.currentPrice)/gapDollars:null;sig={i,time:bar.time,m,base,gapFill:fill};break}}if(sig){const trade=simulate(day,sig.i+1,sig.m,getTradingProfile(symbol).minStopAtr,2);setups.push({symbol,date,bench,dailyBias:db,gapPct:gap,gapFill:sig.gapFill,rvol:sig.m.rvol,rs:sig.m.relativeStrengthPct,shortScore:sig.base.shortScore,time:sig.time,trade})}}}catch(e){skipped.push({symbol,error:e instanceof Error?e.message:String(e)})}}
const bins=[{name:'<25%',lo:-99,hi:.25},{name:'25-50%',lo:.25,hi:.5},{name:'50-75%',lo:.5,hi:.75},{name:'75-100%',lo:.75,hi:1},{name:'>=100%',lo:1,hi:99}].map(b=>({bin:b.name,...stats(setups.filter(x=>x.gapFill!==null&&x.gapFill>=b.lo&&x.gapFill<b.hi))}));const thresholds=[0,.25,.5,.65,.75,.85,1].map(t=>({minGapFill:t,...stats(setups.filter(x=>x.gapFill!==null&&x.gapFill>=t))}));const result={range:{from:FROM,to:TO},setupCount:setups.length,bins,thresholds,setups,skipped};await fs.writeFile('backtest-output-v6-gapfill/result.json',JSON.stringify(result,null,2));await fs.writeFile('backtest-output-v6-gapfill/setups.csv',['symbol,date,time,bias,gapPct,gapFill,rvol,rs,score,outcome,netR',...setups.map(x=>[x.symbol,x.date,x.time,x.dailyBias,x.gapPct,x.gapFill,x.rvol,x.rs,x.shortScore,x.trade.outcome,x.trade.netR].join(','))].join('\n'));console.log(JSON.stringify({setupCount:setups.length,bins,thresholds,skipped},null,2));
