import fs from 'node:fs/promises';
import { buildProfiledDayTradeDecision } from '../src/decisionV6';
import { computeIntradayMetrics, getSessionPhase, type IntradayBar, type DayTradeDecisionInput, type DayTradeDecision } from '../src/intraday';
import { getTradingProfile, WATCHLIST } from '../src/tradingProfiles';

const RAW_FROM='2026-08-17', TEST_FROM='2026-08-31', TO='2026-09-15', DAILY_FROM='2026-03-01';
const OPEN=570,CLOSE=960,COST_BPS_SIDE=2,ACCOUNT=100000,BASE_RISK_USD=500,CHUNK_DAYS=6;
type Raw=IntradayBar&{epoch:number}; type Daily={date:string;close:number};
const epoch=(s:string)=>Math.floor(new Date(`${s}T00:00:00Z`).getTime()/1000);
const ymd=(d:Date)=>d.toISOString().slice(0,10);
const addDays=(s:string,n:number)=>ymd(new Date(new Date(`${s}T00:00:00Z`).getTime()+n*86400000));
const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const ma=(a:number[],n:number)=>a.length>=n?mean(a.slice(-n)):null;
const hhmm=(m:number)=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
const sleep=(n:number)=>new Promise(r=>setTimeout(r,n));
function ny(ms:number){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms));const g=(t:string)=>p.find(x=>x.type===t)?.value??'';const time=`${g('hour')}:${g('minute')}`;const[h,m]=time.split(':').map(Number);return{date:`${g('year')}-${g('month')}-${g('day')}`,time,minute:h*60+m}}
async function yahoo(symbol:string,interval:'1m'|'1d',from:string,to:string){const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?period1=${epoch(from)}&period2=${epoch(to)}&interval=${interval}&includePrePost=false&events=div%2Csplits`;for(let attempt=0;attempt<3;attempt++){const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0 stock-dashboard-v634-canonical','Accept':'application/json'}});if(r.ok){const j:any=await r.json(),x=j?.chart?.result?.[0];if(!x)throw new Error(`${symbol} ${interval} no data`);const q=x.indicators?.quote?.[0]??{};if(interval==='1d'){const out:Daily[]=[];for(let k=0;k<(x.timestamp??[]).length;k++){const c=q.close?.[k];if(Number.isFinite(c))out.push({date:new Date(x.timestamp[k]*1000).toISOString().slice(0,10),close:+c})}return out}const out:Raw[]=[];for(let k=0;k<(x.timestamp??[]).length;k++){const o=q.open?.[k],h=q.high?.[k],l=q.low?.[k],c=q.close?.[k],v=q.volume?.[k];if(![o,h,l,c].every(Number.isFinite))continue;const p=ny(x.timestamp[k]*1000);if(p.minute<OPEN||p.minute>=CLOSE)continue;out.push({...p,epoch:x.timestamp[k]*1000,open:+o,high:+h,low:+l,close:+c,volume:Number(v)||0})}return out;}if(attempt===2)throw new Error(`${symbol} ${interval} HTTP ${r.status}`);await sleep(700*(attempt+1));}return [] as any}
async function oneMinuteRange(symbol:string){const all:Raw[]=[];for(let from=RAW_FROM;from<TO;from=addDays(from,CHUNK_DAYS)){const to=addDays(from,CHUNK_DAYS)<TO?addDays(from,CHUNK_DAYS):TO;const part=await yahoo(symbol,'1m',from,to) as Raw[];all.push(...part);await sleep(100);}const by=new Map<number,Raw>();for(const b of all)by.set(b.epoch,b);return [...by.values()].sort((a,b)=>a.epoch-b.epoch)}
function group(a:Raw[]){const m=new Map<string,Raw[]>();for(const b of a){if(!m.has(b.date))m.set(b.date,[]);m.get(b.date)!.push(b)}return m}
function aggregateDay(one:Raw[]):Raw[]{const buckets=new Map<number,Raw[]>();for(const b of one){const bs=OPEN+Math.floor((b.minute-OPEN)/5)*5;if(!buckets.has(bs))buckets.set(bs,[]);buckets.get(bs)!.push(b)}const out:Raw[]=[];for(const[bs,x]of [...buckets.entries()].sort((a,b)=>a[0]-b[0])){if(x.length<4)continue;const f=x[0],l=x.at(-1)!;out.push({date:f.date,time:hhmm(bs),minute:bs,epoch:f.epoch,open:f.open,high:Math.max(...x.map(z=>z.high)),low:Math.min(...x.map(z=>z.low)),close:l.close,volume:x.reduce((s,z)=>s+z.volume,0)})}return out}
function aggregateMap(oneMap:Map<string,Raw[]>){const m=new Map<string,Raw[]>();for(const[d,b]of oneMap)m.set(d,aggregateDay(b));return m}
function bias(d:Daily[],date:string):'LONG'|'SHORT'|'NEUTRAL'{const p=d.filter(x=>x.date<date).map(x=>x.close);if(p.length<60)return'NEUTRAL';const c=p.at(-1)!,m20=ma(p,20)!,m60=ma(p,60)!;return c>m20&&m20>m60?'LONG':c<m20&&m20<m60?'SHORT':'NEUTRAL'}
function market(s:Daily[],q:Daily[],date:string):'RISK_ON'|'NEUTRAL'|'RISK_OFF'{const a=s.filter(x=>x.date<date).map(x=>x.close),b=q.filter(x=>x.date<date).map(x=>x.close);if(a.length<50||b.length<50)return'NEUTRAL';const ac=a.at(-1)!,bc=b.at(-1)!,a20=ma(a,20)!,a50=ma(a,50)!,b20=ma(b,20)!,b50=ma(b,50)!;if(ac>a20&&a20>a50&&bc>b20&&b20>b50)return'RISK_ON';if(ac<a20&&a20<a50&&bc<b20&&b20<b50)return'RISK_OFF';return'NEUTRAL'}
function priorHistory(map:Map<string,Raw[]>,date:string){const dates=[...map.keys()].filter(d=>d<date).sort().slice(-10);return dates.flatMap(d=>map.get(d)??[])}
function simulate(one:Raw[],entryMinute:number,d:DayTradeDecision,targetKey:'target1'|'target2'){const fillBar=one.find(b=>b.minute===entryMinute);if(!fillBar||d.entry===null||d.stop===null||d.riskPerShare===null||d[targetKey]===null)return null;const fill=fillBar.open,stop=d.stop,origRisk=d.riskPerShare,origTarget=d[targetKey]!;const ratio=Math.abs(origTarget-d.entry)/origRisk;const risk=d.direction==='LONG'?fill-stop:stop-fill;if(risk<=0)return null;const target=d.direction==='LONG'?fill+ratio*risk:fill-ratio*risk;let exit=one.at(-1)!.close,outcome='EOD',exitTime=one.at(-1)!.time;for(const b of one){if(b.minute<entryMinute)continue;const hs=d.direction==='LONG'?b.low<=stop:b.high>=stop;const ht=d.direction==='LONG'?b.high>=target:b.low<=target;if(hs){exit=stop;outcome=ht?'STOP_SAME_MINUTE':'STOP';exitTime=b.time;break}if(ht){exit=target;outcome='TARGET';exitTime=b.time;break}}const grossR=d.direction==='LONG'?(exit-fill)/risk:(fill-exit)/risk;const costR=((fill+exit)*(COST_BPS_SIDE/10000))/risk;const netR=grossR-costR;const shares=d.suggestedShares;const pnl=(d.direction==='LONG'?(exit-fill):(fill-exit))*shares-shares*(fill+exit)*(COST_BPS_SIDE/10000);return{fill,stop,target,outcome,exitTime,netR,pnl,baseR:pnl/BASE_RISK_USD}}
function stats(t:any[]){const r=t.map(x=>x.tp2?.netR).filter(Number.isFinite),base=t.map(x=>x.tp2?.baseR).filter(Number.isFinite),w=r.filter((x:number)=>x>0),l=r.filter((x:number)=>x<0),pos=w.reduce((a:number,b:number)=>a+b,0),neg=-l.reduce((a:number,b:number)=>a+b,0);let eq=0,peak=0,dd=0;for(const x of base){eq+=x;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq)}return{trades:r.length,winRate:r.length?w.length/r.length*100:0,avgTradeR:mean(r),avgBaseR:mean(base),totalBaseR:base.reduce((a:number,b:number)=>a+b,0),profitFactor:neg?pos/neg:null,maxDrawdownBaseR:dd}}
const setup=(label:string)=>label.includes('EVENT REVERSAL')?'EVENT_SHORT':label.includes('B+ PROBE')?'B+':label.includes('A CONFIRMED')?'A_CONFIRMED':label.includes('A+ Profile')?'A+':'OTHER';
const windowOf=(m:number)=>m<615?'EARLY':m<660?'CORE':m<720?'CONTINUATION':'LATE';

await fs.mkdir('backtest-output-v634-canonical-1m',{recursive:true});
const[spyDaily,qqqDaily]=await Promise.all([yahoo('SPY','1d',DAILY_FROM,TO) as Promise<Daily[]>,yahoo('QQQ','1d',DAILY_FROM,TO) as Promise<Daily[]>]);
const benches=[...new Set(WATCHLIST.map(s=>getTradingProfile(s).benchmark))];const bench1=new Map<string,Map<string,Raw[]>>(),bench5=new Map<string,Map<string,Raw[]>>();
for(const b of benches){const one=group(await oneMinuteRange(b));bench1.set(b,one);bench5.set(b,aggregateMap(one));}
const trades:any[]=[],skipped:any[]=[];
for(const symbol of WATCHLIST){try{const profile=getTradingProfile(symbol),oneMap=group(await oneMinuteRange(symbol)),fiveMap=aggregateMap(oneMap),daily=await yahoo(symbol,'1d',DAILY_FROM,TO) as Daily[],b5=bench5.get(profile.benchmark)!;const dates=[...oneMap.keys()].filter(d=>d>=TEST_FROM&&d<TO).sort();for(const date of dates){const one=oneMap.get(date)??[],five=fiveMap.get(date)??[],bfive=b5.get(date)??[];if(one.length<300||five.length<60||bfive.length<60)continue;const db=bias(daily,date),mode=market(spyDaily,qqqDaily,date),shPrior=priorHistory(fiveMap,date),bhPrior=priorHistory(b5,date);let taken=false;for(const bar of five){if(taken)break;const observed=bar.minute+4,entryMinute=observed+1;if(entryMinute>=CLOSE)continue;const completed=five.filter(x=>x.minute<=bar.minute),bcompleted=bfive.filter(x=>x.minute<=bar.minute);const m=computeIntradayMetrics([...shPrior,...completed],[...bhPrior,...bcompleted]);m.stale=false;m.marketOpen=true;m.phase=getSessionPhase(bar.minute,'Mon');const input:DayTradeDecisionInput={metrics:m,dailyBias:db,marketMode:mode,accountSizeUsd:ACCOUNT,riskPerTradePct:.5,dailyMaxLossPct:1.5,realizedPnlUsd:0,maxAllocationPct:25,bid:null,ask:null,hasCatalyst:false};const d=buildProfiledDayTradeDecision(input,profile);if(d.direction==='WAIT'||d.entry===null||d.stop===null||d.target1===null||d.target2===null||!d.riskPerShare||d.suggestedShares<=0)continue;const tp1=simulate(one,entryMinute,d,'target1'),tp2=simulate(one,entryMinute,d,'target2');if(!tp1||!tp2)continue;trades.push({symbol,date,dailyBias:db,market:mode,benchmark:profile.benchmark,signalBar:bar.time,observedAt:hhmm(observed),entryTime:hhmm(entryMinute),direction:d.direction,label:d.label,setup:setup(d.label),window:windowOf(bar.minute),rvol:m.rvol,rs:m.relativeStrengthPct,longScore:d.longScore,shortScore:d.shortScore,scoreLead:d.longScore-d.shortScore,suggestedRiskUsd:d.suggestedRiskUsd,tp1,tp2});taken=true;}}}catch(e){skipped.push({symbol,error:e instanceof Error?e.message:String(e)})}}
const split='2026-09-08';
const categories=(key:string)=>Object.fromEntries([...new Set(trades.map(x=>String(x[key])))].sort().map(v=>[v,stats(trades.filter(x=>String(x[key])===v))]));
const result={range:{rawFrom:RAW_FROM,testFrom:TEST_FROM,toExclusive:TO},method:'canonical Yahoo 1m only -> self-aggregated completed 5m decisions -> next 1m open fill -> 1m exits; 2 bps/side; same-minute stop first',overall:stats(trades),calibration:stats(trades.filter(x=>x.date<split)),validation:stats(trades.filter(x=>x.date>=split)),bySetup:categories('setup'),byWindow:categories('window'),byDailyBias:categories('dailyBias'),byMarket:categories('market'),bySymbol:categories('symbol'),trades,skipped};
await fs.writeFile('backtest-output-v634-canonical-1m/result.json',JSON.stringify(result,null,2));
await fs.writeFile('backtest-output-v634-canonical-1m/trades.csv',['symbol,date,signalBar,observedAt,entryTime,direction,setup,window,dailyBias,market,rvol,rs,longScore,shortScore,scoreLead,label,tp2R,tp2BaseR,tp2Outcome,tp2Exit',...trades.map(x=>[x.symbol,x.date,x.signalBar,x.observedAt,x.entryTime,x.direction,x.setup,x.window,x.dailyBias,x.market,x.rvol,x.rs,x.longScore,x.shortScore,x.scoreLead,JSON.stringify(x.label),x.tp2.netR,x.tp2.baseR,x.tp2.outcome,x.tp2.exitTime].join(','))].join('\n'));
console.log(JSON.stringify({overall:result.overall,calibration:result.calibration,validation:result.validation,bySetup:result.bySetup,byWindow:result.byWindow,skipped},null,2));