import fs from 'node:fs/promises';
import { buildDayTradeDecision, computeIntradayMetrics, getSessionPhase, type DayTradeDecisionInput, type IntradayBar, type DayTradeDecision } from '../src/intraday';
import { applyTradingProfile, getTradingProfile, WATCHLIST } from '../src/tradingProfiles';
import { buildProfiledDayTradeDecision } from '../src/decisionV6';

const FROM='2026-07-17',TO='2026-09-15',DAILY_FROM='2026-03-01',OPEN=570,CLOSE=960,COST_BPS_SIDE=2;
type Raw=IntradayBar&{epoch:number};type Daily={date:string;close:number};
const epoch=(s:string)=>Math.floor(new Date(`${s}T00:00:00Z`).getTime()/1000);const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;const ma=(a:number[],n:number)=>a.length>=n?mean(a.slice(-n)):null;const sleep=(n:number)=>new Promise(r=>setTimeout(r,n));
function ny(ms:number){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms));const g=(t:string)=>p.find(x=>x.type===t)?.value??'';const time=`${g('hour')}:${g('minute')}`;const[h,m]=time.split(':').map(Number);return{date:`${g('year')}-${g('month')}-${g('day')}`,time,minute:h*60+m}}
async function chart(s:string,i:'5m'|'1d'){const f=i==='5m'?FROM:DAILY_FROM,u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(s)}?period1=${epoch(f)}&period2=${epoch(TO)}&interval=${i}&includePrePost=false&events=div%2Csplits`;const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0 stock-dashboard-v6-portfolio','Accept':'application/json'}});if(!r.ok)throw new Error(`${s} ${i} HTTP ${r.status}`);const j:any=await r.json(),x=j?.chart?.result?.[0];if(!x)throw new Error(`${s} no data`);const q=x.indicators?.quote?.[0]??{};if(i==='1d'){const o:Daily[]=[];for(let k=0;k<(x.timestamp??[]).length;k++){const c=q.close?.[k];if(Number.isFinite(c))o.push({date:new Date(x.timestamp[k]*1000).toISOString().slice(0,10),close:+c})}return o}const o:Raw[]=[];for(let k=0;k<(x.timestamp??[]).length;k++){const a=q.open?.[k],h=q.high?.[k],l=q.low?.[k],c=q.close?.[k],v=q.volume?.[k];if(![a,h,l,c].every(Number.isFinite))continue;const p=ny(x.timestamp[k]*1000);if(p.minute<OPEN||p.minute>=CLOSE)continue;o.push({...p,epoch:x.timestamp[k]*1000,open:+a,high:+h,low:+l,close:+c,volume:Number(v)||0})}return o.sort((a,b)=>a.epoch-b.epoch)}
function group(a:Raw[]){const m=new Map<string,Raw[]>();for(const b of a){if(!m.has(b.date))m.set(b.date,[]);m.get(b.date)!.push(b)}return m}function bias(d:Daily[],date:string):'LONG'|'SHORT'|'NEUTRAL'{const p=d.filter(x=>x.date<date).map(x=>x.close);if(p.length<60)return'NEUTRAL';const c=p.at(-1)!,m20=ma(p,20)!,m60=ma(p,60)!;return c>m20&&m20>m60?'LONG':c<m20&&m20<m60?'SHORT':'NEUTRAL'}function market(s:Daily[],q:Daily[],date:string):'RISK_ON'|'NEUTRAL'|'RISK_OFF'{const a=s.filter(x=>x.date<date).map(x=>x.close),b=q.filter(x=>x.date<date).map(x=>x.close);if(a.length<50||b.length<50)return'NEUTRAL';const ac=a.at(-1)!,bc=b.at(-1)!,a20=ma(a,20)!,a50=ma(a,50)!,b20=ma(b,20)!,b50=ma(b,50)!;if(ac>a20&&a20>a50&&bc>b20&&b20>b50)return'RISK_ON';if(ac<a20&&a20<a50&&bc<b20&&b20<b50)return'RISK_OFF';return'NEUTRAL'}
function simulate(day:Raw[],idx:number,d:DayTradeDecision,targetKey:'target1'|'target2'){const fill=day[idx].open,signalEntry=d.entry!,stop=d.stop!,origRisk=d.riskPerShare!,origTarget=d[targetKey]!;const ratio=Math.abs(origTarget-signalEntry)/origRisk;const risk=d.direction==='LONG'?fill-stop:stop-fill;if(risk<=0)return null;const target=d.direction==='LONG'?fill+ratio*risk:fill-ratio*risk;let exit=day.at(-1)!.close,outcome='EOD',exitTime=day.at(-1)!.time;for(let j=idx;j<day.length;j++){const b=day[j];const hs=d.direction==='LONG'?b.low<=stop:b.high>=stop;const ht=d.direction==='LONG'?b.high>=target:b.low<=target;if(hs){exit=stop;outcome=ht?'STOP_SAME_BAR':'STOP';exitTime=b.time;break}if(ht){exit=target;outcome='TARGET';exitTime=b.time;break}}const gross=d.direction==='LONG'?(exit-fill)/risk:(fill-exit)/risk,cost=(fill*(COST_BPS_SIDE*2/10000))/risk;return{fill,stop,target,ratio,outcome,exitTime,netR:gross-cost}}
function stats(t:any[],field:'tp1'|'tp2'){const r=t.map(x=>x[field]?.netR).filter((x:any)=>Number.isFinite(x)),w=r.filter((x:number)=>x>0),l=r.filter((x:number)=>x<0),pos=w.reduce((a:number,b:number)=>a+b,0),neg=-l.reduce((a:number,b:number)=>a+b,0);let eq=0,peak=0,dd=0;for(const x of r){eq+=x;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq)}return{trades:r.length,winRate:r.length?w.length/r.length*100:0,avgR:mean(r),totalR:r.reduce((a:number,b:number)=>a+b,0),profitFactor:neg?pos/neg:null,maxDrawdownR:dd}}
const breakdown=(t:any[],field:'tp1'|'tp2')=>({bySymbol:Object.fromEntries(WATCHLIST.map(s=>[s,stats(t.filter(x=>x.symbol===s),field)])),byDirection:{LONG:stats(t.filter(x=>x.direction==='LONG'),field),SHORT:stats(t.filter(x=>x.direction==='SHORT'),field)},event:stats(t.filter(x=>x.isEvent),field),normal:stats(t.filter(x=>!x.isEvent),field)});

await fs.mkdir('backtest-output-current-v6',{recursive:true});const[spy,qqq]=await Promise.all([chart('SPY','1d') as Promise<Daily[]>,chart('QQQ','1d') as Promise<Daily[]>]);const benches=[...new Set(WATCHLIST.map(s=>getTradingProfile(s).benchmark))],bm=new Map<string,Map<string,Raw[]>>();for(const b of benches){try{bm.set(b,group(await chart(b,'5m') as Raw[]));await sleep(100)}catch(e){console.warn('bench',b,e)}}const baseline:any[]=[],v6:any[]=[],skipped:any[]=[];
for(const symbol of WATCHLIST){try{const profile=getTradingProfile(symbol),bp=bm.get(profile.benchmark);if(!bp)continue;const bars=await chart(symbol,'5m') as Raw[];await sleep(100);const daily=await chart(symbol,'1d') as Daily[];await sleep(100);const mp=group(bars),dates=[...mp.keys()].sort();for(let di=10;di<dates.length;di++){const date=dates[di],day=mp.get(date)!,bd=bp.get(date)??[];if(day.length<30||bd.length<30)continue;const db=bias(daily,date),mode=market(spy,qqq,date);let gotBase=false,gotV6=false;for(let i=0;i<day.length;i++){if(gotBase&&gotV6)break;const bar=day[i];if(bar.minute<585||i+1>=day.length)continue;const prior=dates.slice(di-10,di),sh:IntradayBar[]=[],bh:IntradayBar[]=[];for(const d of prior){sh.push(...(mp.get(d)??[]));bh.push(...(bp.get(d)??[]))}sh.push(...day.slice(0,i+1));bh.push(...bd.filter(x=>x.minute<=bar.minute));const m=computeIntradayMetrics(sh,bh);m.stale=false;m.marketOpen=true;m.phase=getSessionPhase(bar.minute,'Mon');const input:DayTradeDecisionInput={metrics:m,dailyBias:db,marketMode:mode,accountSizeUsd:100000,riskPerTradePct:.5,dailyMaxLossPct:1.5,realizedPnlUsd:0,maxAllocationPct:25,bid:null,ask:null,hasCatalyst:false};if(!gotBase){const base=applyTradingProfile(input,buildDayTradeDecision(input),profile);if(base.direction!=='WAIT'&&base.entry!==null&&base.stop!==null&&base.target1!==null&&base.target2!==null&&base.riskPerShare){const tp1=simulate(day,i+1,base,'target1'),tp2=simulate(day,i+1,base,'target2');if(tp1&&tp2){baseline.push({symbol,date,signalTime:bar.time,direction:base.direction,label:base.label,dailyBias:db,market:mode,tp1,tp2});gotBase=true}}}if(!gotV6){const d=buildProfiledDayTradeDecision(input,profile);if(d.direction!=='WAIT'&&d.entry!==null&&d.stop!==null&&d.target1!==null&&d.target2!==null&&d.riskPerShare){const tp1=simulate(day,i+1,d,'target1'),tp2=simulate(day,i+1,d,'target2');if(tp1&&tp2){v6.push({symbol,date,signalTime:bar.time,direction:d.direction,label:d.label,isEvent:d.label.includes('EVENT REVERSAL'),dailyBias:db,market:mode,tp1,tp2});gotV6=true}}}}}}catch(e){skipped.push({symbol,error:e instanceof Error?e.message:String(e)})}}
const result={range:{from:FROM,to:TO},friction:'2 bps/side, next 5m open, same-bar stop first',baseline:{tp1:stats(baseline,'tp1'),tp2:stats(baseline,'tp2'),tp1Breakdown:breakdown(baseline.map(x=>({...x,isEvent:false})),'tp1'),tp2Breakdown:breakdown(baseline.map(x=>({...x,isEvent:false})),'tp2')},v6:{tp1:stats(v6,'tp1'),tp2:stats(v6,'tp2'),tp1Breakdown:breakdown(v6,'tp1'),tp2Breakdown:breakdown(v6,'tp2')},delta:{tp1AvgR:stats(v6,'tp1').avgR-stats(baseline,'tp1').avgR,tp2AvgR:stats(v6,'tp2').avgR-stats(baseline,'tp2').avgR},trades:{baseline,v6},skipped};await fs.writeFile('backtest-output-current-v6/result.json',JSON.stringify(result,null,2));await fs.writeFile('backtest-output-current-v6/v6-trades.csv',['symbol,date,signal,direction,label,tp1R,tp1Outcome,tp2R,tp2Outcome',...v6.map(x=>[x.symbol,x.date,x.signalTime,x.direction,x.label,x.tp1.netR,x.tp1.outcome,x.tp2.netR,x.tp2.outcome].join(','))].join('\n'));console.log(JSON.stringify({baseline:result.baseline.tp2,v6:result.v6.tp2,delta:result.delta,v6Directions:result.v6.tp2Breakdown.byDirection,v6Event:result.v6.tp2Breakdown.event,skipped},null,2));
