import fs from 'node:fs/promises';

const STOCKS={
  NVDA:'https://raw.githubusercontent.com/getdata-finance/nvda-5m-ohlcv-stocks-historical-data/main/NVDA_5m.csv',
  AMD:'https://raw.githubusercontent.com/getdata-finance/amd-5m-ohlcv-stocks-historical-data/main/AMD_5m.csv',
  AVGO:'https://raw.githubusercontent.com/getdata-finance/avgo-5m-ohlcv-stocks-historical-data/main/AVGO_5m.csv',
  AAPL:'https://raw.githubusercontent.com/getdata-finance/aapl-5m-ohlcv-stocks-historical-data/main/AAPL_5m.csv',
  MSFT:'https://raw.githubusercontent.com/getdata-finance/msft-5m-ohlcv-stocks-historical-data/main/MSFT_5m.csv',
};
const NAS='https://raw.githubusercontent.com/getdata-finance/nas100-5m-ohlcv-index-historical-data/main/NAS100_5m.csv';
const SPX='https://raw.githubusercontent.com/getdata-finance/spx500-5m-ohlcv-index-historical-data/main/SPX500_5m.csv';
const OPEN=570,CLOSE=960,OR_END=585,V3_START=600,MIN_SCORE=80,MIN_LEAD=15;
const ACCOUNT=15000,RISK_PCT=.5,MAX_ALLOC=25;
const sum=a=>a.reduce((x,y)=>x+y,0),mean=a=>a.length?sum(a)/a.length:null,clamp=(x,a,b)=>Math.min(Math.max(x,a),b);

function ny(d){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(d);const g=t=>p.find(x=>x.type===t)?.value??'';const time=`${g('hour')}:${g('minute')}`;const [h,m]=time.split(':').map(Number);return{date:`${g('year')}-${g('month')}-${g('day')}`,time,minute:h*60+m}}
function parse(t){const l=t.trim().split(/\r?\n/),h=l[0].split(',').map(x=>x.trim().toLowerCase()),ix=Object.fromEntries(h.map((x,i)=>[x,i])),o=[];for(let i=1;i<l.length;i++){if(!l[i].trim())continue;const c=l[i].split(',');let r=c[ix.datetime];if(!/[zZ]|[+-]\d\d:?\d\d$/.test(r))r+='Z';const d=new Date(r);if(Number.isNaN(d.getTime()))continue;const q=ny(d),b={...q,epoch:d.getTime(),open:+c[ix.open],high:+c[ix.high],low:+c[ix.low],close:+c[ix.close],volume:+c[ix.volume]||0};if([b.open,b.high,b.low,b.close].every(Number.isFinite))o.push(b)}return o.sort((a,b)=>a.epoch-b.epoch)}
async function get(u){const r=await fetch(u,{headers:{'User-Agent':'stock-dashboard-backtest-v3'}});if(!r.ok)throw Error(`${u}: ${r.status}`);return r.text()}
const reg=a=>a.filter(b=>b.minute>=OPEN&&b.minute<CLOSE);
function byDate(a){const m=new Map;for(const b of a){if(!m.has(b.date))m.set(b.date,[]);m.get(b.date).push(b)}for(const v of m.values())v.sort((a,b)=>a.epoch-b.epoch);return m}
function daily(a){return[...byDate(reg(a)).entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,x])=>({date,open:x[0].open,high:Math.max(...x.map(z=>z.high)),low:Math.min(...x.map(z=>z.low)),close:x.at(-1).close,volume:sum(x.map(z=>z.volume))}))}
function ma(a,n){return a.length<n?null:mean(a.slice(-n).map(x=>x.close))}
function bias(d,date){const p=d.filter(x=>x.date<date);if(p.length<60)return'NEUTRAL';const c=p.at(-1).close,a=ma(p,20),b=ma(p,60);return c>a&&a>b?'LONG':c<a&&a<b?'SHORT':'NEUTRAL'}
function market(sd,nd,date){const s=sd.filter(x=>x.date<date),n=nd.filter(x=>x.date<date);if(s.length<50||n.length<50)return'NEUTRAL';const sc=s.at(-1).close,nc=n.at(-1).close,s20=ma(s,20),s50=ma(s,50),n20=ma(n,20),n50=ma(n,50);if(sc>s20&&s20>s50&&nc>n20&&n20>n50)return'RISK_ON';if(sc<s20&&s20<s50&&nc<n20&&n20<n50)return'RISK_OFF';return'NEUTRAL'}
function vw(a){let pv=0,v=0;return a.map(b=>{const t=(b.high+b.low+b.close)/3;if(b.volume>0){pv+=t*b.volume;v+=b.volume}return v?pv/v:b.close})}
function atr(a,n=14){if(a.length<=n)return null;const s=a.slice(-(n+1)),r=[];for(let i=1;i<s.length;i++)r.push(Math.max(s[i].high-s[i].low,Math.abs(s[i].high-s[i-1].close),Math.abs(s[i].low-s[i-1].close)));return mean(r)}
function phase(m){return m<585?'OPENING':m<690?'PRIMARY':m<840?'MIDDAY':m<930?'SECONDARY':m<960?'CLOSING':'CLOSED'}
function pf(p){return p==='PRIMARY'||p==='SECONDARY'?1:p==='MIDDAY'?.6:p==='CLOSING'?.5:p==='OPENING'?.35:0}
function rvol(map,dates,date,min){const i=dates.indexOf(date),p=dates.slice(Math.max(0,i-10),i);if(i<0||p.length<3)return 0;const cur=sum((map.get(date)||[]).filter(b=>b.minute<=min).map(b=>b.volume)),hist=p.map(d=>sum((map.get(d)||[]).filter(b=>b.minute<=min).map(b=>b.volume))).filter(x=>x>0),av=mean(hist);return av?cur/av:0}
function bench(day,min){const x=day.filter(b=>b.minute<=min);if(!x.length)return{ret:null,above:null};const v=vw(x).at(-1);return{ret:(x.at(-1).close/x[0].open-1)*100,above:x.at(-1).close>v}}
function metrics(x,oh,ol,rv,bm){const price=x.at(-1).close,v=vw(x),vwap=v.at(-1),slope=v.length>=4?v.at(-1)>v.at(-4):null,a=atr(x)??Math.max(price*.002,.01),above=price>vwap,below=price<vwap,brokeH=price>oh,brokeL=price<ol,near=Math.abs(price-vwap)<=a*.35,rs=bm.ret===null?null:(price/x[0].open-1)*100-bm.ret,recent=x.slice(-4);return{price,vwap,slope,atr:a,above,below,brokeH,brokeL,near,rs,rv,orHigh:oh,orLow:ol,recentLow:Math.min(...recent.map(b=>b.low)),recentHigh:Math.max(...recent.map(b=>b.high)),phase:phase(x.at(-1).minute),minute:x.at(-1).minute,benchmarkAboveVwap:bm.above}}
function baseline(m,d,mode){let L=(d==='LONG'?10:d==='NEUTRAL'?5:0)+(mode==='RISK_ON'?10:mode==='NEUTRAL'?5:0),S=(d==='SHORT'?10:d==='NEUTRAL'?5:0)+(mode==='RISK_OFF'?10:mode==='NEUTRAL'?5:0);if(m.benchmarkAboveVwap===true)L+=10;if(m.benchmarkAboveVwap===false)S+=10;if(m.above)L+=12;if(m.below)S+=12;if(m.slope===true)L+=8;if(m.slope===false)S+=8;if(m.brokeH)L+=15;else if(m.above&&m.near)L+=10;if(m.brokeL)S+=15;else if(m.below&&m.near)S+=10;const vp=m.rv>=2?15:m.rv>=1.5?12:m.rv>=1.2?8:m.rv>=1?4:0;L+=vp;S+=vp;if(m.rs!==null){L+=m.rs>=.5?10:m.rs>=.2?7:m.rs>0?3:0;S+=m.rs<=-.5?10:m.rs<=-.2?7:m.rs<0?3:0}L+=2;S+=2;const f=pf(m.phase),tp=f>=1?5:f>=.6?3:f>0?1:0;L=clamp(L+tp,0,100);S=clamp(S+tp,0,100);let dir='WAIT';if(L>=80&&L-S>=15)dir='LONG';else if(S>=80&&S-L>=15)dir='SHORT';return{...m,L,S,dir}}
function v3(m,d,mode){const vs=m.rv>=2?10:m.rv>=1.5?8:m.rv>=1.2?6:m.rv>=1?3:0,lr=m.rs===null?0:m.rs>=.5?10:m.rs>=.2?7:m.rs>0?4:0,sr=m.rs===null?0:m.rs<=-.5?10:m.rs<=-.2?7:m.rs<0?4:0;let L=(d==='LONG'?10:d==='NEUTRAL'?5:0)+(mode==='RISK_ON'?15:mode==='NEUTRAL'?8:0)+(m.benchmarkAboveVwap===true?15:0)+(m.above?12:0)+(m.slope===true?8:0)+(m.brokeH?20:m.above&&m.near?12:0)+vs+lr;let S=(d==='SHORT'?10:d==='NEUTRAL'?3:0)+(mode==='RISK_OFF'?15:mode==='NEUTRAL'?5:0)+(m.benchmarkAboveVwap===false?15:0)+(m.below?12:0)+(m.slope===false?8:0)+(m.brokeL?20:0)+vs+sr;L=clamp(L,0,100);S=clamp(S,0,100);const longOK=m.minute>=V3_START&&mode!=='RISK_OFF'&&m.above&&m.slope===true&&m.benchmarkAboveVwap===true&&m.rs>0&&(m.brokeH||(m.above&&m.near));const shortOK=m.minute>=V3_START&&d!=='LONG'&&mode!=='RISK_ON'&&m.below&&m.slope===false&&m.benchmarkAboveVwap===false&&m.rs<0&&m.brokeL;let dir='WAIT';if(longOK&&L>=MIN_SCORE&&L-S>=MIN_LEAD)dir='LONG';else if(shortOK&&S>=MIN_SCORE&&S-L>=MIN_LEAD)dir='SHORT';return{...m,L,S,dir}}
function levels(s,e){const a=s.atr;if(s.dir==='LONG'){const c=[s.vwap-a*.25,s.orHigh-a*.2,s.recentLow-a*.1].filter(v=>v<e),st=Math.max(.01,Math.min(c.length?Math.max(...c):e-a*.5,e-a*.35)),r=Math.max(.01,e-st);return{stop:st,risk:r,t1:e+1.5*r,t2:e+2*r}}const c=[s.vwap+a*.25,s.orLow+a*.2,s.recentHigh+a*.1].filter(v=>v>e),st=Math.max(e+a*.35,c.length?Math.min(...c):e+a*.5),r=Math.max(.01,st-e);return{stop:st,risk:r,t1:e-1.5*r,t2:e-2*r}}
function trade(day,i,s){const e=day[i].open,l=levels(s,e);let out='EOD',ex=day.at(-1).close,xt=day.at(-1).time;for(let j=i;j<day.length;j++){const b=day[j];if(s.dir==='LONG'){if(b.low<=l.stop){out='STOP';ex=l.stop;xt=b.time;break}if(b.high>=l.t1){out='TP1';ex=l.t1;xt=b.time;break}}else{if(b.high>=l.stop){out='STOP';ex=l.stop;xt=b.time;break}if(b.low<=l.t1){out='TP1';ex=l.t1;xt=b.time;break}}}const R=s.dir==='LONG'?(ex-e)/l.risk:(e-ex)/l.risk,rb=ACCOUNT*(RISK_PCT/100)*pf(s.phase),sh=Math.max(0,Math.min(Math.floor(rb/l.risk),Math.floor(ACCOUNT*(MAX_ALLOC/100)/e))),pnl=sh*(s.dir==='LONG'?ex-e:e-ex);return{entry:e,...l,outcome:out,exit:ex,exitTime:xt,r:R,shares:sh,pnl}}
function stats(t){const w=t.filter(x=>x.r>0),l=t.filter(x=>x.r<0),pr=sum(w.map(x=>x.r)),nr=-sum(l.map(x=>x.r)),gw=sum(w.map(x=>x.pnl)),gl=-sum(l.map(x=>x.pnl));let c=0,p=0,dd=0,ls=0,mls=0;for(const x of t){c+=x.pnl;p=Math.max(p,c);dd=Math.max(dd,p-c);if(x.r<0){ls++;mls=Math.max(mls,ls)}else ls=0}return{trades:t.length,wins:w.length,losses:l.length,winRate:t.length?w.length/t.length*100:0,avgR:mean(t.map(x=>x.r))??0,totalR:sum(t.map(x=>x.r)),profitFactorR:nr?pr/nr:null,profitFactorUsd:gl?gw/gl:null,totalPnl:sum(t.map(x=>x.pnl)),maxDrawdownUsd:dd,maxLossStreak:mls,tp1Rate:t.length?t.filter(x=>x.outcome==='TP1').length/t.length*100:0,stopRate:t.length?t.filter(x=>x.outcome==='STOP').length/t.length*100:0}}
function run(symbol,stock,nas,spx,name,fn,start){const sb=byDate(reg(stock)),nb=byDate(reg(nas)),xb=byDate(reg(spx)),dates=[...sb.keys()].sort(),common=dates.filter(d=>nb.has(d)&&xb.has(d)),sd=daily(stock),nd=daily(nas),xd=daily(spx),tr=[];for(const date of common){const d=bias(sd,date),mode=market(xd,nd,date),day=sb.get(date),bd=nb.get(date),op=day.filter(b=>b.minute>=OPEN&&b.minute<OR_END);if(op.length<3)continue;const oh=Math.max(...op.map(b=>b.high)),ol=Math.min(...op.map(b=>b.low));for(let i=0;i<day.length-1;i++){const b=day[i];if(b.minute<start)continue;const bm=bench(bd,b.minute);if(bm.ret===null)continue;const m=metrics(day.slice(0,i+1),oh,ol,rvol(sb,dates,date,b.minute),bm),s=fn(m,d,mode);if(s.dir==='WAIT')continue;tr.push({symbol,strategy:name,date,signalTime:b.time,entryTime:day[i+1].time,direction:s.dir,longScore:s.L,shortScore:s.S,dailyBias:d,marketMode:mode,phase:s.phase,rvol:s.rv,rs:s.rs,...trade(day,i+1,s)});break}}return{symbol,sample:`${common[0]} to ${common.at(-1)}`,sessions:common.length,summary:stats(tr),trades:tr}}
function agg(r){const t=r.flatMap(x=>x.trades);return{summary:stats(t),bySymbol:Object.fromEntries(r.map(x=>[x.symbol,x.summary]))}}

async function main(){const[nasTxt,spxTxt]=await Promise.all([get(NAS),get(SPX)]),nas=parse(nasTxt),spx=parse(spxTxt),rows=[];for(const[symbol,url]of Object.entries(STOCKS)){try{rows.push([symbol,parse(await get(url))])}catch(e){console.warn(`Skipping ${symbol}: ${e.message}`)}}if(!rows.length)throw Error('No stock data loaded');const base=[],time=[],newv=[];for(const[symbol,stock]of rows){console.log(`Running ${symbol}`);base.push(run(symbol,stock,nas,spx,'baseline_v2',baseline,OR_END));time.push(run(symbol,stock,nas,spx,'baseline_after_10',baseline,V3_START));newv.push(run(symbol,stock,nas,spx,'v3_hard_filters',v3,V3_START))}const report={methodology:{version:'v3-ab-cross-sectional',lockedHypotheses:['No new entries before 10:00 ET','Long/short asymmetric; short requires stricter daily/market alignment','VWAP direction, benchmark VWAP, relative strength and setup validity are hard filters'],execution:'completed 5m signal bar -> next 5m open; TP1=1.5R; stop=-1R; EOD exit; same-bar stop/target => stop first',benchmark:'NAS100 proxy for QQQ; SPX500 + NAS100 market regime',limitations:'No historical bid/ask; no slippage/fees; public volume is tick volume; NVDA generated the hypotheses so AMD/AVGO/AAPL/MSFT are cross-sectional validation, not a time-based holdout.'},baseline:agg(base),timeFilterOnly:agg(time),v3:agg(newv),perSymbol:Object.fromEntries(rows.map(([s])=>[s,{baseline:base.find(x=>x.symbol===s),timeFilterOnly:time.find(x=>x.symbol===s),v3:newv.find(x=>x.symbol===s)}]))};await fs.mkdir('backtest-output-v3',{recursive:true});await fs.writeFile('backtest-output-v3/strategy-comparison.json',JSON.stringify(report,null,2));const all=[...base.flatMap(x=>x.trades),...time.flatMap(x=>x.trades),...newv.flatMap(x=>x.trades)],cols=['symbol','strategy','date','signalTime','entryTime','direction','longScore','shortScore','dailyBias','marketMode','phase','rvol','rs','entry','stop','t1','t2','outcome','exit','exitTime','r','shares','pnl'];await fs.writeFile('backtest-output-v3/trades-all.csv',[cols.join(','),...all.map(t=>cols.map(k=>t[k]??'').join(','))].join('\n'));console.log('\n=== V3 A/B SUMMARY ===');console.log(JSON.stringify({baseline:report.baseline,timeFilterOnly:report.timeFilterOnly,v3:report.v3},null,2))}
main().catch(e=>{console.error(e);process.exit(1)});
