import fs from 'node:fs/promises';
import { buildDayTradeDecision, computeIntradayMetrics, getSessionPhase, type DayTradeDecisionInput, type IntradayBar } from '../src/intraday';
import { getTradingProfile, WATCHLIST } from '../src/tradingProfiles';

const FROM='2026-07-17', TO='2026-09-15', DAILY_FROM='2026-03-01';
const OPEN=570,CLOSE=960,OR_END=585,COST_BPS_PER_SIDE=2;
const CALIBRATION:Record<string,string>={
  AAPL:'QQQ',MSFT:'QQQ',GOOGL:'QQQ',AMZN:'QQQ',META:'QQQ',NFLX:'QQQ',
  ADBE:'IGV',NOW:'IGV',PANW:'IGV',CRWD:'IGV',PLTR:'IGV',
  QCOM:'SOXX',INTC:'SOXX',ARM:'SOXX',TSM:'SOXX',MRVL:'SOXX',SMCI:'SOXX',
  ANET:'XLK',COHR:'XLK',CIEN:'XLK',
};
const HOLDOUT=Object.fromEntries(WATCHLIST.map(s=>[s,getTradingProfile(s).benchmark]));
type Raw=IntradayBar&{epoch:number}; type Daily={date:string;close:number};
const epoch=(s:string)=>Math.floor(new Date(`${s}T00:00:00Z`).getTime()/1000);
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0; const ma=(x:number[],n:number)=>x.length>=n?mean(x.slice(-n)):null;
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function ny(ms:number){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms));const g=(t:string)=>p.find(x=>x.type===t)?.value??'';const time=`${g('hour')}:${g('minute')}`;const[h,m]=time.split(':').map(Number);return{date:`${g('year')}-${g('month')}-${g('day')}`,time,minute:h*60+m}}
async function chart(symbol:string,interval:'5m'|'1d') {const from=interval==='5m'?FROM:DAILY_FROM;const url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?period1=${epoch(from)}&period2=${epoch(TO)}&interval=${interval}&includePrePost=false&events=div%2Csplits`;const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 stock-dashboard-crosssection','Accept':'application/json'}});if(!r.ok)throw new Error(`${symbol} ${interval} HTTP ${r.status}`);const j:any=await r.json();const x=j?.chart?.result?.[0];if(!x)throw new Error(`${symbol} ${interval} no data`);const q=x.indicators?.quote?.[0]??{};if(interval==='1d'){const out:Daily[]=[];for(let i=0;i<(x.timestamp??[]).length;i++){const c=q.close?.[i];if(Number.isFinite(c))out.push({date:new Date(x.timestamp[i]*1000).toISOString().slice(0,10),close:+c})}return out;}const out:Raw[]=[];for(let i=0;i<(x.timestamp??[]).length;i++){const o=q.open?.[i],h=q.high?.[i],l=q.low?.[i],c=q.close?.[i],v=q.volume?.[i];if(![o,h,l,c].every(Number.isFinite))continue;const p=ny(x.timestamp[i]*1000);if(p.minute<OPEN||p.minute>=CLOSE)continue;out.push({...p,epoch:x.timestamp[i]*1000,open:+o,high:+h,low:+l,close:+c,volume:Number(v)||0})}return out.sort((a,b)=>a.epoch-b.epoch)}
function group(a:Raw[]){const m=new Map<string,Raw[]>();for(const b of a){if(!m.has(b.date))m.set(b.date,[]);m.get(b.date)!.push(b)}return m}
function bias(d:Daily[],date:string):'LONG'|'SHORT'|'NEUTRAL'{const p=d.filter(x=>x.date<date).map(x=>x.close);if(p.length<60)return'NEUTRAL';const c=p.at(-1)!,m20=ma(p,20)!,m60=ma(p,60)!;return c>m20&&m20>m60?'LONG':c<m20&&m20<m60?'SHORT':'NEUTRAL'}
function market(spy:Daily[],qqq:Daily[],date:string):'RISK_ON'|'NEUTRAL'|'RISK_OFF'{const s=spy.filter(x=>x.date<date).map(x=>x.close),q=qqq.filter(x=>x.date<date).map(x=>x.close);if(s.length<50||q.length<50)return'NEUTRAL';const sc=s.at(-1)!,qc=q.at(-1)!,s20=ma(s,20)!,s50=ma(s,50)!,q20=ma(q,20)!,q50=ma(q,50)!;if(sc>s20&&s20>s50&&qc>q20&&q20>q50)return'RISK_ON';if(sc<s20&&s20<s50&&qc<q20&&q20<q50)return'RISK_OFF';return'NEUTRAL'}
function simulate(day:Raw[],idx:number,m:any,stopAtr:number,targetR:number){const entry=day[idx].open,atr=m.intradayAtr??Math.max(entry*.002,.01);const c=[m.vwap!==null?m.vwap+atr*.25:null,m.orLow!==null?m.orLow+atr*.2:null,m.recentHigh!==null?m.recentHigh+atr*.1:null].filter((v):v is number=>v!==null&&v>entry);const structural=c.length?Math.min(...c):entry+atr*.5;const stop=Math.max(entry+atr*stopAtr,structural),risk=Math.max(.01,stop-entry),target=entry-targetR*risk;let exit=day.at(-1)!.close,outcome='EOD',exitTime=day.at(-1)!.time;for(let j=idx;j<day.length;j++){const b=day[j],hs=b.high>=stop,ht=b.low<=target;if(hs){exit=stop;outcome=ht?'STOP_SAME_BAR':'STOP';exitTime=b.time;break}if(ht){exit=target;outcome='TARGET';exitTime=b.time;break}}const gross=(entry-exit)/risk,cost=(entry*(COST_BPS_PER_SIDE*2/10000))/risk;return{entry,stop,target,risk,outcome,exit,exitTime,grossR:gross,netR:gross-cost}}
function stats(t:any[]){const r=t.map(x=>x.trade.netR),w=r.filter(x=>x>0),l=r.filter(x=>x<0),pos=w.reduce((a,b)=>a+b,0),neg=-l.reduce((a,b)=>a+b,0);let eq=0,peak=0,dd=0;for(const x of r){eq+=x;peak=Math.max(peak,eq);dd=Math.max(dd,peak-eq)}return{trades:t.length,winRate:t.length?w.length/t.length*100:0,avgR:mean(r),totalR:r.reduce((a,b)=>a+b,0),profitFactor:neg?pos/neg:null,maxDrawdownR:dd}}

await fs.mkdir('backtest-output-v6-crosssection',{recursive:true});
const [spy,qqq]=await Promise.all([chart('SPY','1d') as Promise<Daily[]>,chart('QQQ','1d') as Promise<Daily[]>]);
const benches=[...new Set([...Object.values(CALIBRATION),...Object.values(HOLDOUT)])];const benchMaps=new Map<string,Map<string,Raw[]>>();for(const b of benches){try{benchMaps.set(b,group(await chart(b,'5m') as Raw[]));await sleep(150)}catch(e){console.warn('bench skip',b,e)}}
async function buildCases(universe:Record<string,string>,setName:string){const cases:any[]=[];const skipped:any[]=[];for(const[symbol,bench]of Object.entries(universe)){try{const bars=await chart(symbol,'5m') as Raw[];await sleep(120);const daily=await chart(symbol,'1d') as Daily[];await sleep(120);const map=group(bars),dates=[...map.keys()].sort(),bm=benchMaps.get(bench);if(!bm)throw new Error('benchmark unavailable');for(let di=1;di<dates.length;di++){const date=dates[di],day=map.get(date)!,prev=map.get(dates[di-1])!,bday=bm.get(date)??[];if(day.length<30||prev.length<30||bday.length<30)continue;const db=bias(daily,date),mode=market(spy,qqq,date);if(db!=='LONG'||mode==='RISK_ON')continue;const gap=(day[0].open/prev.at(-1)!.close-1)*100;if(gap<2)continue;const timeline:any[]=[];for(let i=0;i<day.length;i++){const bar=day[i];if(bar.minute<OR_END)continue;const priorDates=dates.slice(Math.max(0,di-10),di),sh:IntradayBar[]=[],bh:IntradayBar[]=[];for(const d of priorDates){sh.push(...(map.get(d)??[]));bh.push(...(bm.get(d)??[]))}sh.push(...day.slice(0,i+1));bh.push(...bday.filter(x=>x.minute<=bar.minute));const m=computeIntradayMetrics(sh,bh);m.stale=false;m.marketOpen=true;m.phase=getSessionPhase(bar.minute,'Mon');const input:DayTradeDecisionInput={metrics:m,dailyBias:db,marketMode:mode,accountSizeUsd:100000,riskPerTradePct:.5,dailyMaxLossPct:1.5,realizedPnlUsd:0,maxAllocationPct:25,bid:null,ask:null,hasCatalyst:false};const base=buildDayTradeDecision(input);timeline.push({i,time:bar.time,m,base})}cases.push({set:setName,symbol,bench,date,gap,day,timeline,stopAtr:getTradingProfile(symbol).minStopAtr??.65})}}catch(e){skipped.push({symbol,error:e instanceof Error?e.message:String(e)})}}return{cases,skipped}}
const cal=await buildCases(CALIBRATION,'calibration'),hold=await buildCases(HOLDOUT,'holdout');
const grid:any[]=[];for(const minGap of[3,4,5])for(const minRvol of[1.5,2,2.5])for(const maxRs of[-1,-1.5,-2])for(const minMinute of[600,615,630])for(const stopExtra of[0,.15])for(const targetR of[1.75,2])grid.push({minGap,minRvol,maxRs,minMinute,stopExtra,targetR});
function run(cfg:any,cases:any[]){const trades:any[]=[];for(const c of cases){if(c.gap<cfg.minGap)continue;let sig:any=null;for(const x of c.timeline){const m=x.m,b=x.base;const ready=(m.latestMinute??0)>=cfg.minMinute&&(m.rvol??0)>=cfg.minRvol&&m.currentPrice!==null&&m.vwap!==null&&m.currentPrice<m.vwap&&m.vwapSlopeUp===false&&m.benchmarkAboveVwap===false&&(m.relativeStrengthPct??Infinity)<=cfg.maxRs&&m.orReady&&m.orLow!==null&&m.currentPrice<m.orLow&&b.shortScore>=80&&b.shortScore-b.longScore>=15;if(ready&&x.i+1<c.day.length){sig=x;break}}if(sig){const trade=simulate(c.day,sig.i+1,sig.m,c.stopAtr+cfg.stopExtra,cfg.targetR);trades.push({set:c.set,symbol:c.symbol,date:c.date,gap:c.gap,signalTime:sig.time,rvol:sig.m.rvol,rs:sig.m.relativeStrengthPct,shortScore:sig.base.shortScore,longScore:sig.base.longScore,trade})}}return trades}
const rows=grid.map(cfg=>{const ct=run(cfg,cal.cases),ht=run(cfg,hold.cases),cs=stats(ct),hs=stats(ht);const objective=(cs.trades>=5?cs.avgR:cs.avgR-.5)+(cs.profitFactor??0)*.05-Math.max(0,cs.maxDrawdownR-4)*.03;return{cfg,calibration:cs,holdout:hs,objective,calTrades:ct,holdTrades:ht}}).sort((a,b)=>b.objective-a.objective);
const eligible=rows.filter(x=>x.calibration.trades>=5&&x.calibration.avgR>0&&(x.calibration.profitFactor??0)>1);const best=eligible[0]??rows[0];const robustTop=rows.slice(0,20);const positiveCal=robustTop.filter(x=>x.calibration.trades>=3&&x.calibration.avgR>0&&(x.calibration.profitFactor??0)>1).length;const positiveHold=robustTop.filter(x=>x.holdout.trades>=1&&x.holdout.avgR>0&&(x.holdout.profitFactor??0)>1).length;
const currentCfg={minGap:5,minRvol:2,maxRs:-2,minMinute:615,stopExtra:0,targetR:2};const current={cfg:currentCfg,calibration:stats(run(currentCfg,cal.cases)),holdout:stats(run(currentCfg,hold.cases)),calTrades:run(currentCfg,cal.cases),holdTrades:run(currentCfg,hold.cases)};
const result={range:{from:FROM,to:TO},caseCounts:{calibration:cal.cases.length,holdout:hold.cases.length},skipped:{calibration:cal.skipped,holdout:hold.skipped},current,best:{cfg:best.cfg,calibration:best.calibration,holdout:best.holdout,calTrades:best.calTrades,holdTrades:best.holdTrades},top20Robustness:{positiveCalibration:positiveCal,positiveHoldout:positiveHold,total:20},top20:robustTop.map(x=>({cfg:x.cfg,calibration:x.calibration,holdout:x.holdout}))};
await fs.writeFile('backtest-output-v6-crosssection/result.json',JSON.stringify(result,null,2));await fs.writeFile('backtest-output-v6-crosssection/top20.csv',['gap,rvol,maxRs,minMinute,stopExtra,targetR,calN,calAvgR,calPF,holdN,holdAvgR,holdPF',...robustTop.map(x=>[x.cfg.minGap,x.cfg.minRvol,x.cfg.maxRs,x.cfg.minMinute,x.cfg.stopExtra,x.cfg.targetR,x.calibration.trades,x.calibration.avgR,x.calibration.profitFactor??'',x.holdout.trades,x.holdout.avgR,x.holdout.profitFactor??''].join(','))].join('\n'));console.log(JSON.stringify(result,null,2));
