import fs from 'node:fs/promises';
import { buildDayTradeDecision, computeIntradayMetrics, getSessionPhase, type DayTradeDecisionInput, type IntradayBar } from '../src/intraday';
import { getTradingProfile } from '../src/tradingProfiles';

const FROM='2026-07-17', TO='2026-09-15', DAILY_FROM='2026-03-01';
const OPEN=570,CLOSE=960;
const CASES=[
  {symbol:'ORCL',date:'2026-09-11',bench:'IGV'},
  {symbol:'ANET',date:'2026-08-05',bench:'XLK'},
];
type Raw=IntradayBar&{epoch:number}; type Daily={date:string;close:number};
const epoch=(s:string)=>Math.floor(new Date(`${s}T00:00:00Z`).getTime()/1000);
const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const ma=(a:number[],n:number)=>a.length>=n?mean(a.slice(-n)):null;
function ny(ms:number){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms));const g=(t:string)=>p.find(x=>x.type===t)?.value??'';const time=`${g('hour')}:${g('minute')}`;const[h,m]=time.split(':').map(Number);return{date:`${g('year')}-${g('month')}-${g('day')}`,time,minute:h*60+m}}
async function chart(symbol:string,interval:'5m'|'1d'){const from=interval==='5m'?FROM:DAILY_FROM;const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?period1=${epoch(from)}&period2=${epoch(TO)}&interval=${interval}&includePrePost=false&events=div%2Csplits`;const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0 stock-dashboard-persistence','Accept':'application/json'}});if(!r.ok)throw new Error(`${symbol} ${interval} HTTP ${r.status}`);const j:any=await r.json(),x=j?.chart?.result?.[0];if(!x)throw new Error(`${symbol} no data`);const q=x.indicators?.quote?.[0]??{};if(interval==='1d'){const o:Daily[]=[];for(let i=0;i<(x.timestamp??[]).length;i++){const c=q.close?.[i];if(Number.isFinite(c))o.push({date:new Date(x.timestamp[i]*1000).toISOString().slice(0,10),close:+c})}return o}const o:Raw[]=[];for(let i=0;i<(x.timestamp??[]).length;i++){const a=q.open?.[i],h=q.high?.[i],l=q.low?.[i],c=q.close?.[i],v=q.volume?.[i];if(![a,h,l,c].every(Number.isFinite))continue;const p=ny(x.timestamp[i]*1000);if(p.minute<OPEN||p.minute>=CLOSE)continue;o.push({...p,epoch:x.timestamp[i]*1000,open:+a,high:+h,low:+l,close:+c,volume:Number(v)||0})}return o.sort((a,b)=>a.epoch-b.epoch)}
function group(a:Raw[]){const m=new Map<string,Raw[]>();for(const b of a){if(!m.has(b.date))m.set(b.date,[]);m.get(b.date)!.push(b)}return m}
function bias(d:Daily[],date:string):'LONG'|'SHORT'|'NEUTRAL'{const p=d.filter(x=>x.date<date).map(x=>x.close);if(p.length<60)return'NEUTRAL';const c=p.at(-1)!,m20=ma(p,20)!,m60=ma(p,60)!;return c>m20&&m20>m60?'LONG':c<m20&&m20<m60?'SHORT':'NEUTRAL'}
function market(spy:Daily[],qqq:Daily[],date:string):'RISK_ON'|'NEUTRAL'|'RISK_OFF'{const a=spy.filter(x=>x.date<date).map(x=>x.close),b=qqq.filter(x=>x.date<date).map(x=>x.close);if(a.length<50||b.length<50)return'NEUTRAL';const ac=a.at(-1)!,bc=b.at(-1)!,a20=ma(a,20)!,a50=ma(a,50)!,b20=ma(b,20)!,b50=ma(b,50)!;if(ac>a20&&a20>a50&&bc>b20&&b20>b50)return'RISK_ON';if(ac<a20&&a20<a50&&bc<b20&&b20<b50)return'RISK_OFF';return'NEUTRAL'}
function simulate(day:Raw[],idx:number,m:any,stopAtr=.65,targetR=2){const entry=day[idx].open,atr=m.intradayAtr??Math.max(entry*.002,.01),c=[m.vwap!==null?m.vwap+atr*.25:null,m.orLow!==null?m.orLow+atr*.2:null,m.recentHigh!==null?m.recentHigh+atr*.1:null].filter((v):v is number=>v!==null&&v>entry),struct=c.length?Math.min(...c):entry+atr*.5,stop=Math.max(entry+atr*stopAtr,struct),risk=Math.max(.01,stop-entry),target=entry-targetR*risk;let exit=day.at(-1)!.close,out='EOD',time=day.at(-1)!.time;for(let j=idx;j<day.length;j++){const b=day[j],hs=b.high>=stop,ht=b.low<=target;if(hs){exit=stop;out=ht?'STOP_SAME_BAR':'STOP';time=b.time;break}if(ht){exit=target;out='TARGET';time=b.time;break}}return{entry,stop,stopPct:(stop-entry)/entry*100,target,outcome:out,exitTime:time,netR:(entry-exit)/risk-(entry*.0004)/risk}}

await fs.mkdir('backtest-output-v6-persistence',{recursive:true});
const [spyD,qqqD]=await Promise.all([chart('SPY','1d') as Promise<Daily[]>,chart('QQQ','1d') as Promise<Daily[]>]);
const results:any[]=[];
for(const c of CASES){const[bars,daily,bbars]=await Promise.all([chart(c.symbol,'5m') as Promise<Raw[]>,chart(c.symbol,'1d') as Promise<Daily[]>,chart(c.bench,'5m') as Promise<Raw[]>]);const mp=group(bars),bm=group(bbars),dates=[...mp.keys()].sort(),di=dates.indexOf(c.date),day=mp.get(c.date)??[],bd=bm.get(c.date)??[];if(di<1||!day.length||!bd.length)throw new Error(`${c.symbol} case unavailable`);const db=bias(daily,c.date),mode=market(spyD,qqqD,c.date),timeline:any[]=[];for(let i=0;i<day.length;i++){const bar=day[i];if(bar.minute<585)continue;const prior=dates.slice(Math.max(0,di-10),di),sh:IntradayBar[]=[],bh:IntradayBar[]=[];for(const d of prior){sh.push(...(mp.get(d)??[]));bh.push(...(bm.get(d)??[]))}sh.push(...day.slice(0,i+1));bh.push(...bd.filter(x=>x.minute<=bar.minute));const m=computeIntradayMetrics(sh,bh);m.stale=false;m.marketOpen=true;m.phase=getSessionPhase(bar.minute,'Mon');const input:DayTradeDecisionInput={metrics:m,dailyBias:db,marketMode:mode,accountSizeUsd:100000,riskPerTradePct:.5,dailyMaxLossPct:1.5,realizedPnlUsd:0,maxAllocationPct:25,bid:null,ask:null,hasCatalyst:false};const base=buildDayTradeDecision(input);const belowOr=m.orLow!==null&&m.currentPrice!==null&&m.currentPrice<m.orLow;const highBelowOr=m.orLow!==null&&bar.high<m.orLow;const priorRows=timeline.slice(-2);const consecutive2=belowOr&&priorRows.length>=1&&priorRows.at(-1).belowOr;const consecutive3=consecutive2&&priorRows.length>=2&&priorRows.at(-2).belowOr;const closeDistanceAtr=m.orLow!==null&&m.currentPrice!==null&&m.intradayAtr? (m.orLow-m.currentPrice)/m.intradayAtr:null;timeline.push({i,time:bar.time,open:bar.open,high:bar.high,low:bar.low,close:bar.close,orLow:m.orLow,vwap:m.vwap,atr:m.intradayAtr,rvol:m.rvol,rs:m.relativeStrengthPct,benchmarkBelow:m.benchmarkAboveVwap===false,belowOr,highBelowOr,consecutive2,consecutive3,closeDistanceAtr,longScore:base.longScore,shortScore:base.shortScore})}
const grid:any[]=[];for(const confirmBars of[1,2,3])for(const requireHighBelow of[false,true])for(const minMinute of[615,620,625,630])for(const minDistanceAtr of[0,.25,.5]){let sig:any=null;for(let k=0;k<timeline.length;k++){const x=timeline[k];const persist=confirmBars===1?x.belowOr:confirmBars===2?x.consecutive2:x.consecutive3;const ready=x.time>=`${String(Math.floor(minMinute/60)).padStart(2,'0')}:${String(minMinute%60).padStart(2,'0')}`&&persist&&(!requireHighBelow||x.highBelowOr)&&(x.rvol??0)>=2&&(x.rs??Infinity)<=-2&&x.benchmarkBelow&&x.shortScore>=80&&x.shortScore-x.longScore>=15&&(x.closeDistanceAtr??0)>=minDistanceAtr;if(ready&&x.i+1<day.length){sig=x;break}}grid.push({confirmBars,requireHighBelow,minMinute,minDistanceAtr,signalTime:sig?.time??null,trade:sig?simulate(day,sig.i+1,sig,getTradingProfile(c.symbol).minStopAtr,2):null})}
results.push({case:c,dailyBias:db,market:mode,timeline:timeline.filter(x=>x.time>='09:45'&&x.time<='10:45'),grid})}
const combos:any[]=[];for(let i=0;i<results[0].grid.length;i++){const o=results[0].grid[i],a=results[1].grid[i];combos.push({confirmBars:o.confirmBars,requireHighBelow:o.requireHighBelow,minMinute:o.minMinute,minDistanceAtr:o.minDistanceAtr,orclSignal:o.signalTime,orclR:o.trade?.netR??null,anetSignal:a.signalTime,anetR:a.trade?.netR??null,keepsOrcl:Boolean(o.signalTime),filtersAnet:!a.signalTime})}
const passing=combos.filter(x=>x.keepsOrcl&&x.filtersAnet).sort((a,b)=>(a.minMinute-b.minMinute)||(a.confirmBars-b.confirmBars)||(Number(a.requireHighBelow)-Number(b.requireHighBelow))||(a.minDistanceAtr-b.minDistanceAtr));
const result={cases:results.map(x=>({case:x.case,dailyBias:x.dailyBias,market:x.market,timeline:x.timeline})),passingCount:passing.length,passing,allCombos:combos};await fs.writeFile('backtest-output-v6-persistence/result.json',JSON.stringify(result,null,2));await fs.writeFile('backtest-output-v6-persistence/combos.csv',['confirmBars,requireHighBelow,minMinute,minDistanceAtr,orclSignal,orclR,anetSignal,anetR,keepsOrcl,filtersAnet',...combos.map(x=>[x.confirmBars,x.requireHighBelow,x.minMinute,x.minDistanceAtr,x.orclSignal??'',x.orclR??'',x.anetSignal??'',x.anetR??'',x.keepsOrcl,x.filtersAnet].join(','))].join('\n'));console.log(JSON.stringify({passingCount:passing.length,passing:passing.slice(0,20),orclTimeline:results[0].timeline.filter((x:any)=>x.time>='10:00'&&x.time<='10:35'),anetTimeline:results[1].timeline.filter((x:any)=>x.time>='10:00'&&x.time<='10:35')},null,2));
