import fs from 'node:fs/promises';
import { buildProfiledDayTradeDecision } from '../src/decisionV6';
import { computeIntradayMetrics, getSessionPhase, type IntradayBar, type DayTradeDecisionInput } from '../src/intraday';
import { getTradingProfile } from '../src/tradingProfiles';
const DATE='2026-09-14',TO='2026-09-15',HIST_FROM='2026-08-25',DAILY_FROM='2026-03-01',OPEN=570,CLOSE=960,SYMS=['ORCL','RMBS','MU','SNDK'];
type Raw=IntradayBar&{epoch:number};type Daily={date:string;close:number};const epoch=(s:string)=>Math.floor(new Date(`${s}T00:00:00Z`).getTime()/1000);const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;const ma=(a:number[],n:number)=>a.length>=n?mean(a.slice(-n)):null;const hh=(m:number)=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
function ny(ms:number){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms));const g=(t:string)=>p.find(x=>x.type===t)?.value??'';const time=`${g('hour')}:${g('minute')}`;const[h,m]=time.split(':').map(Number);return{date:`${g('year')}-${g('month')}-${g('day')}`,time,minute:h*60+m}}
async function chart(s:string,i:'1m'|'5m'|'1d',f:string,t:string){const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(s)}?period1=${epoch(f)}&period2=${epoch(t)}&interval=${i}&includePrePost=false&events=div%2Csplits`;const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0 v634-feed-diagnostic','Accept':'application/json'}});if(!r.ok)throw new Error(`${s} ${i} ${r.status}`);const j:any=await r.json(),x=j?.chart?.result?.[0],q=x?.indicators?.quote?.[0]??{};if(i==='1d'){const o:Daily[]=[];for(let k=0;k<(x?.timestamp??[]).length;k++){const c=q.close?.[k];if(Number.isFinite(c))o.push({date:new Date(x.timestamp[k]*1000).toISOString().slice(0,10),close:+c})}return o}const o:Raw[]=[];for(let k=0;k<(x?.timestamp??[]).length;k++){const a=q.open?.[k],h=q.high?.[k],l=q.low?.[k],c=q.close?.[k],v=q.volume?.[k];if(![a,h,l,c].every(Number.isFinite))continue;const p=ny(x.timestamp[k]*1000);if(p.minute>=OPEN&&p.minute<CLOSE)o.push({...p,epoch:x.timestamp[k]*1000,open:+a,high:+h,low:+l,close:+c,volume:Number(v)||0})}return o.sort((a,b)=>a.epoch-b.epoch)}
function group(a:Raw[]){const m=new Map<string,Raw[]>();for(const b of a){if(!m.has(b.date))m.set(b.date,[]);m.get(b.date)!.push(b)}return m}function bias(d:Daily[]):'LONG'|'SHORT'|'NEUTRAL'{const p=d.filter(x=>x.date<DATE).map(x=>x.close);const c=p.at(-1)!,m20=ma(p,20)!,m60=ma(p,60)!;return c>m20&&m20>m60?'LONG':c<m20&&m20<m60?'SHORT':'NEUTRAL'}function market(s:Daily[],q:Daily[]):'RISK_ON'|'NEUTRAL'|'RISK_OFF'{const a=s.filter(x=>x.date<DATE).map(x=>x.close),b=q.filter(x=>x.date<DATE).map(x=>x.close),ac=a.at(-1)!,bc=b.at(-1)!,a20=ma(a,20)!,a50=ma(a,50)!,b20=ma(b,20)!,b50=ma(b,50)!;return ac>a20&&a20>a50&&bc>b20&&b20>b50?'RISK_ON':ac<a20&&a20<a50&&bc<b20&&b20<b50?'RISK_OFF':'NEUTRAL'}
function aggregate(one:Raw[]){const m=new Map<number,Raw[]>();for(const b of one.filter(x=>x.date===DATE)){const bs=OPEN+Math.floor((b.minute-OPEN)/5)*5;if(!m.has(bs))m.set(bs,[]);m.get(bs)!.push(b)}return [...m.entries()].sort((a,b)=>a[0]-b[0]).map(([bs,x])=>({date:DATE,time:hh(bs),minute:bs,epoch:x[0].epoch,open:x[0].open,high:Math.max(...x.map(z=>z.high)),low:Math.min(...x.map(z=>z.low)),close:x.at(-1)!.close,volume:x.reduce((s,z)=>s+z.volume,0)} as Raw))}
const prior=(m:Map<string,Raw[]>)=>[...m.keys()].filter(d=>d<DATE).sort().slice(-10).flatMap(d=>m.get(d)??[]);
const[sd,qd]=await Promise.all([chart('SPY','1d',DAILY_FROM,DATE) as Promise<Daily[]>,chart('QQQ','1d',DAILY_FROM,DATE) as Promise<Daily[]>]),mode=market(sd,qd),rows:any[]=[];
for(const symbol of SYMS){const p=getTradingProfile(symbol),db=bias(await chart(symbol,'1d',DAILY_FROM,DATE) as Daily[]),stockHist=group(await chart(symbol,'5m',HIST_FROM,DATE) as Raw[]),benchHist=group(await chart(p.benchmark,'5m',HIST_FROM,DATE) as Raw[]),native=(await chart(symbol,'5m',DATE,TO) as Raw[]).filter(x=>x.date===DATE),bnative=(await chart(p.benchmark,'5m',DATE,TO) as Raw[]).filter(x=>x.date===DATE),agg=aggregate((await chart(symbol,'1m',DATE,TO) as Raw[]).filter(x=>x.date===DATE)),bagg=aggregate((await chart(p.benchmark,'1m',DATE,TO) as Raw[]).filter(x=>x.date===DATE)),sp=prior(stockHist),bp=prior(benchHist);for(let minute=585;minute<=630;minute+=5){const evalFeed=(feed:Raw[],bf:Raw[])=>{const cur=feed.filter(x=>x.minute<=minute),bc=bf.filter(x=>x.minute<=minute);if(!cur.length||!bc.length)return null;const m=computeIntradayMetrics([...sp,...cur],[...bp,...bc]);m.stale=false;m.marketOpen=true;m.phase=getSessionPhase(minute,'Mon');const input:DayTradeDecisionInput={metrics:m,dailyBias:db,marketMode:mode,accountSizeUsd:100000,riskPerTradePct:.5,dailyMaxLossPct:1.5,realizedPnlUsd:0,maxAllocationPct:25,bid:null,ask:null,hasCatalyst:false};const d=buildProfiledDayTradeDecision(input,p);const bar=cur.at(-1)!;return{close:bar.close,volume:bar.volume,rvol:m.rvol,rs:m.relativeStrengthPct,longScore:d.longScore,shortScore:d.shortScore,direction:d.direction,label:d.label}};const n=evalFeed(native,bnative),a=evalFeed(agg,bagg);rows.push({symbol,minute,time:hh(minute),dailyBias:db,market:mode,native:n,aggregated1m:a,closeDiff:n&&a?n.close-a.close:null,volumeRatio:n&&a&&a.volume?n.volume/a.volume:null});}}
await fs.mkdir('diagnostic-v634-feed-2026-09-14',{recursive:true});await fs.writeFile('diagnostic-v634-feed-2026-09-14/compare.json',JSON.stringify(rows,null,2));await fs.writeFile('diagnostic-v634-feed-2026-09-14/compare.csv',['symbol,time,nativeClose,aggClose,closeDiff,nativeVol,aggVol,volRatio,nativeRVOL,aggRVOL,nativeRS,aggRS,nativeLong,aggLong,nativeDir,aggDir,nativeLabel,aggLabel',...rows.map(r=>[r.symbol,r.time,r.native?.close??'',r.aggregated1m?.close??'',r.closeDiff??'',r.native?.volume??'',r.aggregated1m?.volume??'',r.volumeRatio??'',r.native?.rvol??'',r.aggregated1m?.rvol??'',r.native?.rs??'',r.aggregated1m?.rs??'',r.native?.longScore??'',r.aggregated1m?.longScore??'',r.native?.direction??'',r.aggregated1m?.direction??'',JSON.stringify(r.native?.label??''),JSON.stringify(r.aggregated1m?.label??'')].join(','))].join('\n'));console.log(JSON.stringify(rows.filter(r=>r.native?.direction!==r.aggregated1m?.direction||r.native?.label!==r.aggregated1m?.label),null,2));