import fs from 'node:fs/promises';
import { buildProfiledDayTradeDecision } from '../src/decisionV6';
import { computeIntradayMetrics, getSessionPhase, type IntradayBar, type DayTradeDecisionInput, type DayTradeDecision } from '../src/intraday';
import { getTradingProfile, WATCHLIST } from '../src/tradingProfiles';

const DATE='2026-09-14', HIST_FROM='2026-08-25', DAILY_FROM='2026-03-01';
const OPEN=570,CLOSE=960,COST_BPS_SIDE=2,ACCOUNT=100000,BASE_RISK_USD=500;
type Raw=IntradayBar&{epoch:number}; type Daily={date:string;close:number};
const epoch=(s:string)=>Math.floor(new Date(`${s}T00:00:00Z`).getTime()/1000);
const nextDate=(s:string)=>new Date(new Date(`${s}T00:00:00Z`).getTime()+86400000).toISOString().slice(0,10);
const mean=(a:number[])=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
const ma=(a:number[],n:number)=>a.length>=n?mean(a.slice(-n)):null;
const hhmm=(m:number)=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
function ny(ms:number){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(ms));const g=(t:string)=>p.find(x=>x.type===t)?.value??'';const time=`${g('hour')}:${g('minute')}`;const[h,m]=time.split(':').map(Number);return{date:`${g('year')}-${g('month')}-${g('day')}`,time,minute:h*60+m}}
async function chart(symbol:string,interval:'1m'|'5m'|'1d',from:string,to:string){const u=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?period1=${epoch(from)}&period2=${epoch(to)}&interval=${interval}&includePrePost=false&events=div%2Csplits`;const r=await fetch(u,{headers:{'User-Agent':'Mozilla/5.0 stock-dashboard-v634-minute-replay','Accept':'application/json'}});if(!r.ok)throw new Error(`${symbol} ${interval} HTTP ${r.status}`);const j:any=await r.json(),x=j?.chart?.result?.[0];if(!x)throw new Error(`${symbol} ${interval} no data`);const q=x.indicators?.quote?.[0]??{};if(interval==='1d'){const out:Daily[]=[];for(let k=0;k<(x.timestamp??[]).length;k++){const c=q.close?.[k];if(Number.isFinite(c))out.push({date:new Date(x.timestamp[k]*1000).toISOString().slice(0,10),close:+c})}return out}const out:Raw[]=[];for(let k=0;k<(x.timestamp??[]).length;k++){const o=q.open?.[k],h=q.high?.[k],l=q.low?.[k],c=q.close?.[k],v=q.volume?.[k];if(![o,h,l,c].every(Number.isFinite))continue;const p=ny(x.timestamp[k]*1000);if(p.minute<OPEN||p.minute>=CLOSE)continue;out.push({...p,epoch:x.timestamp[k]*1000,open:+o,high:+h,low:+l,close:+c,volume:Number(v)||0})}return out.sort((a,b)=>a.epoch-b.epoch)}
function group(a:Raw[]){const m=new Map<string,Raw[]>();for(const b of a){if(!m.has(b.date))m.set(b.date,[]);m.get(b.date)!.push(b)}return m}
function bias(d:Daily[],date:string):'LONG'|'SHORT'|'NEUTRAL'{const p=d.filter(x=>x.date<date).map(x=>x.close);if(p.length<60)return'NEUTRAL';const c=p.at(-1)!,m20=ma(p,20)!,m60=ma(p,60)!;return c>m20&&m20>m60?'LONG':c<m20&&m20<m60?'SHORT':'NEUTRAL'}
function market(s:Daily[],q:Daily[],date:string):'RISK_ON'|'NEUTRAL'|'RISK_OFF'{const a=s.filter(x=>x.date<date).map(x=>x.close),b=q.filter(x=>x.date<date).map(x=>x.close);if(a.length<50||b.length<50)return'NEUTRAL';const ac=a.at(-1)!,bc=b.at(-1)!,a20=ma(a,20)!,a50=ma(a,50)!,b20=ma(b,20)!,b50=ma(b,50)!;if(ac>a20&&a20>a50&&bc>b20&&b20>b50)return'RISK_ON';if(ac<a20&&a20<a50&&bc<b20&&b20<b50)return'RISK_OFF';return'NEUTRAL'}
function aggregateCompleted(one:Raw[],through:number):Raw[]{const buckets=new Map<number,Raw[]>();for(const b of one){if(b.date!==DATE||b.minute>through)continue;const bs=OPEN+Math.floor((b.minute-OPEN)/5)*5;if(bs+4>through)continue;if(!buckets.has(bs))buckets.set(bs,[]);buckets.get(bs)!.push(b)}const out:Raw[]=[];for(const[bs,x]of [...buckets.entries()].sort((a,b)=>a[0]-b[0])){if(!x.length)continue;const f=x[0],l=x.at(-1)!;out.push({date:DATE,time:hhmm(bs),minute:bs,epoch:f.epoch,open:f.open,high:Math.max(...x.map(z=>z.high)),low:Math.min(...x.map(z=>z.low)),close:l.close,volume:x.reduce((s,z)=>s+z.volume,0)})}return out}
function priorHistory(map:Map<string,Raw[]>,date:string){const dates=[...map.keys()].filter(d=>d<date).sort().slice(-10);return dates.flatMap(d=>map.get(d)??[])}
function findMinute(day:Raw[],minute:number){return day.find(b=>b.minute===minute)??null}
function exitFor(day:Raw[],entryMinute:number,direction:'LONG'|'SHORT',fill:number,stop:number,target:number,shares:number){let exit=day.at(-1)!.close,exitMinute=day.at(-1)!.minute,outcome='EOD';for(const b of day){if(b.minute<entryMinute)continue;const hs=direction==='LONG'?b.low<=stop:b.high>=stop;const ht=direction==='LONG'?b.high>=target:b.low<=target;if(hs){exit=stop;exitMinute=b.minute;outcome=ht?'STOP_SAME_MINUTE':'STOP';break}if(ht){exit=target;exitMinute=b.minute;outcome='TARGET';break}}const gross=direction==='LONG'?(exit-fill)*shares:(fill-exit)*shares;const cost=shares*(fill+exit)*(COST_BPS_SIDE/10000);const pnl=gross-cost;const actualRisk=Math.abs(fill-stop)*shares;return{exit,exitTime:hhmm(exitMinute),outcome,pnl,tradeR:actualRisk>0?pnl/actualRisk:null,baseR:pnl/BASE_RISK_USD}}

await fs.mkdir('replay-output-v634-2026-09-14',{recursive:true});
const targetTo=nextDate(DATE);
const[spyDaily,qqqDaily]=await Promise.all([chart('SPY','1d',DAILY_FROM,DATE) as Promise<Daily[]>,chart('QQQ','1d',DAILY_FROM,DATE) as Promise<Daily[]>]);
const mode=market(spyDaily,qqqDaily,DATE);
const benchmarks=[...new Set(WATCHLIST.map(s=>getTradingProfile(s).benchmark))];
const benchHist=new Map<string,Map<string,Raw[]>>(),bench1m=new Map<string,Raw[]>();
for(const b of benchmarks){benchHist.set(b,group(await chart(b,'5m',HIST_FROM,DATE) as Raw[]));bench1m.set(b,(await chart(b,'1m',DATE,targetTo) as Raw[]).filter(x=>x.date===DATE));}

const timelines:any[]=[],trades:any[]=[],skipped:any[]=[];
for(const symbol of WATCHLIST){try{const profile=getTradingProfile(symbol),hist5=group(await chart(symbol,'5m',HIST_FROM,DATE) as Raw[]),one=(await chart(symbol,'1m',DATE,targetTo) as Raw[]).filter(x=>x.date===DATE),daily=await chart(symbol,'1d',DAILY_FROM,DATE) as Daily[],db=bias(daily,DATE),bh=benchHist.get(profile.benchmark)!,bo=bench1m.get(profile.benchmark)!;if(!one.length){skipped.push({symbol,reason:'no 1m target-day data'});continue}const shPrior=priorHistory(hist5,DATE),bhPrior=priorHistory(bh,DATE);let firstDecision:DayTradeDecision|null=null,decisionObservedMinute:number|null=null;let lastLabel='WARMUP';let lastDirection='WAIT';let pending:any=null;let trade:any=null;
for(let t=OPEN;t<CLOSE;t++){const minuteBar=findMinute(one,t);if(pending&&minuteBar&&t===pending.fillMinute){const d:DayTradeDecision=pending.decision,fill=minuteBar.open,stop=d.stop!;const valid=d.direction==='LONG'?fill>stop:fill<stop;if(valid){const r1=Math.abs(d.target1!-d.entry!)/d.riskPerShare!,r2=Math.abs(d.target2!-d.entry!)/d.riskPerShare!,risk=Math.abs(fill-stop),tp1=d.direction==='LONG'?fill+r1*risk:fill-r1*risk,tp2=d.direction==='LONG'?fill+r2*risk:fill-r2*risk,shares=d.suggestedShares;trade={symbol,date:DATE,dailyBias:db,market:mode,benchmark:profile.benchmark,signalObservedAt:hhmm(decisionObservedMinute!),signalBar:d.latestTime??null,direction:d.direction,label:d.label,longScore:d.longScore,shortScore:d.shortScore,entryTime:hhmm(t),fill,stop,tp1,tp2,shares,suggestedRiskUsd:d.suggestedRiskUsd,actualRiskUsd:shares*risk};firstDecision=d;}else{timelines.push({symbol,time:hhmm(t),event:'ENTRY_CANCELLED_SLIPPED_THROUGH_STOP',price:minuteBar.open,label:d.label});}pending=null;}
const completed=aggregateCompleted(one,t),bcompleted=aggregateCompleted(bo,t);let evaluated=false;if(completed.length&&completed.at(-1)!.minute+4===t&&!firstDecision&&!pending){const m=computeIntradayMetrics([...shPrior,...completed],[...bhPrior,...bcompleted]);m.stale=false;m.marketOpen=true;m.phase=getSessionPhase(m.latestMinute??t,'Mon');const input:DayTradeDecisionInput={metrics:m,dailyBias:db,marketMode:mode,accountSizeUsd:ACCOUNT,riskPerTradePct:.5,dailyMaxLossPct:1.5,realizedPnlUsd:0,maxAllocationPct:25,bid:null,ask:null,hasCatalyst:false};const d=buildProfiledDayTradeDecision(input,profile);lastLabel=d.label;lastDirection=d.direction;evaluated=true;if(d.direction!=='WAIT'&&d.entry!==null&&d.stop!==null&&d.target1!==null&&d.target2!==null&&d.riskPerShare&&d.suggestedShares>0){pending={decision:d,fillMinute:t+1};decisionObservedMinute=t;}}
if(minuteBar)timelines.push({symbol,time:hhmm(t),price:minuteBar.close,evaluated5m:evaluated,direction:lastDirection,label:lastLabel,position:trade?'OPEN':pending?'PENDING':'FLAT'});
}
if(trade&&firstDecision){const tp1=exitFor(one,Number(trade.entryTime.slice(0,2))*60+Number(trade.entryTime.slice(3)),firstDecision.direction as 'LONG'|'SHORT',trade.fill,trade.stop,trade.tp1,trade.shares),tp2=exitFor(one,Number(trade.entryTime.slice(0,2))*60+Number(trade.entryTime.slice(3)),firstDecision.direction as 'LONG'|'SHORT',trade.fill,trade.stop,trade.tp2,trade.shares);trades.push({...trade,tp1Result:tp1,tp2Result:tp2});}
}catch(e){skipped.push({symbol,reason:e instanceof Error?e.message:String(e)})}}
const sum=(xs:number[])=>xs.reduce((a,b)=>a+b,0),tp2Pnl=sum(trades.map(x=>x.tp2Result.pnl)),tp1Pnl=sum(trades.map(x=>x.tp1Result.pnl));
const summary={date:DATE,method:'blind minute replay; decisions only after each completed 5m bar; fills at next 1m open; exits checked each subsequent 1m bar; 2 bps/side; same-minute stop first',watchlist:WATCHLIST,marketMode:mode,signals:trades.length,tp1:{pnlUsd:tp1Pnl,baseR:tp1Pnl/BASE_RISK_USD,wins:trades.filter(x=>x.tp1Result.pnl>0).length,losses:trades.filter(x=>x.tp1Result.pnl<=0).length},tp2:{pnlUsd:tp2Pnl,baseR:tp2Pnl/BASE_RISK_USD,wins:trades.filter(x=>x.tp2Result.pnl>0).length,losses:trades.filter(x=>x.tp2Result.pnl<=0).length},trades,skipped};
await fs.writeFile('replay-output-v634-2026-09-14/summary.json',JSON.stringify(summary,null,2));
await fs.writeFile('replay-output-v634-2026-09-14/trades.csv',['symbol,signalObservedAt,signalBar,direction,label,entryTime,fill,stop,tp1,tp2,shares,actualRiskUsd,tp1Exit,tp1Outcome,tp1Pnl,tp1R,tp2Exit,tp2Outcome,tp2Pnl,tp2R',...trades.map(x=>[x.symbol,x.signalObservedAt,x.signalBar,x.direction,JSON.stringify(x.label),x.entryTime,x.fill,x.stop,x.tp1,x.tp2,x.shares,x.actualRiskUsd,x.tp1Result.exitTime,x.tp1Result.outcome,x.tp1Result.pnl,x.tp1Result.tradeR,x.tp2Result.exitTime,x.tp2Result.outcome,x.tp2Result.pnl,x.tp2Result.tradeR].join(','))].join('\n'));
await fs.writeFile('replay-output-v634-2026-09-14/minute-timeline.csv',['symbol,time,price,evaluated5m,direction,label,position,event',...timelines.map(x=>[x.symbol,x.time,x.price??'',x.evaluated5m??'',x.direction??'',JSON.stringify(x.label??''),x.position??'',x.event??''].join(','))].join('\n'));
console.log(JSON.stringify(summary,null,2));